version: '3'
services:
   db:
     image: mysql:5.7
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: user
       MYSQL_PASSWORD: password
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     volumes:
       - ./public_html/:/var/www/html
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: user
       WORDPRESS_DB_PASSWORD: password
       #WORDPRESS_TABLE_PREFIX: 'nac_'
       WORDPRESS_DEBUG: 'true'
       WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD','direct'); //fix wordpress asking for ftp connection to install plugins
        
        //define log policy
        define( 'WP_DEBUG_LOG', true ); //send logs to /wp-content/debug.log
        define( 'WP_DEBUG_DISPLAY', false ); //don't displat errors on screen

        //set local dev URL
        define( 'WP_HOME', 'http://localhost:8000' );
        define( 'WP_SITEURL', 'http://localhost:8000' );
        
   phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - '8001:80'
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: password
        UPLOAD_LIMIT: 3000000000
   ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    links:
      - wordpress
    environment:
      - DOMAIN=wordpress
      - PORT=80
# volumes:
#     db_data:
